// <auto-generated />
namespace Epicode_U5_W3_D1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AggiuntoControlloLogin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AggiuntoControlloLogin));
        
        string IMigrationMetadata.Id
        {
            get { return "202310131011357_AggiuntoControlloLogin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
